feat:header mobile-view
V-M-AISHNA/Website-Cloning pull request #1
Opened 2023-09-21 11:42 UTC by V-M-AISHNA

![image](https://github.com/V-M-AISHNA/Website-Cloning/assets/142985486/a4ef6631-4a65-48fc-a754-6f121cbcd0f7)

2023-09-22 11:55 UTC, V-M-AISHNA commented
![image](https://github.com/V-M-AISHNA/Website-Cloning/assets/142985486/745522d5-b6f9-4124-bf5a-e7933112b142)
![image](https://github.com/V-M-AISHNA/Website-Cloning/assets/142985486/683b1715-e179-451c-bc7d-6ccb6e23a093)

2023-09-23 15:44 UTC, vonnue-anusha requested changes

2023-09-23 15:44 UTC, vonnue-anusha commented on Airbnb/index.html
> +        <div class="header-container">
Remove header-container and give header-container styling to the header.

2023-09-23 15:44 UTC, vonnue-anusha commented on Airbnb/index.html
> +                <div class="item">
rename item to nav-item

2023-09-28 12:46 UTC, merged