Feat/nav bar
V-M-AISHNA/Website-Cloning pull request #2
Opened 2023-09-23 11:59 UTC by V-M-AISHNA

2023-09-23 12:03 UTC, V-M-AISHNA commented
![image](https://github.com/V-M-AISHNA/Website-Cloning/assets/142985486/0b1af38f-941a-4102-a45a-ca1e459adfb3)
![image](https://github.com/V-M-AISHNA/Website-Cloning/assets/142985486/0f361cdd-bf98-4e07-bb1a-c74033521eed)
![image](https://github.com/V-M-AISHNA/Website-Cloning/assets/142985486/36da817c-9c93-4918-bbb6-5c593871b9f1)
![image](https://github.com/V-M-AISHNA/Website-Cloning/assets/142985486/2dc83456-1dc0-4d66-9e7a-b89cee54374b)

2023-09-23 15:54 UTC, vonnue-anusha requested changes

2023-09-23 15:54 UTC, vonnue-anusha commented on Airbnb/index.html
> +
remove spacing

2023-09-23 15:54 UTC, vonnue-anusha commented on Airbnb/index.html
> +        <div class="main-section">
remove this and give main-section styles to main

2023-09-23 15:54 UTC, vonnue-anusha commented on Airbnb/index.html
> +                <div class="display-total-block">
Are both containers needed?

2023-09-23 15:54 UTC, vonnue-anusha commented on Airbnb/index.html
> +            <div class="card-group">
change class name to cards-container

2023-09-26 12:30 UTC, V-M-AISHNA commented
![image](https://github.com/V-M-AISHNA/Website-Cloning/assets/142985486/24fffe8b-ffad-4af2-a375-039e24d8f9cd)
![image](https://github.com/V-M-AISHNA/Website-Cloning/assets/142985486/004b7e48-ac72-46a7-9040-fe4aa81355c2)

2023-09-28 12:46 UTC, merged